# Generated by Django 3.0.4 on 2020-04-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200401_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooklepage',
            name='show_in_latests',
        ),
        migrations.AddField(
            model_name='gooklepage',
            name='show_in_the_top_of_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gooklepage',
            name='show_in_the_top_of_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gooklepage',
            name='show_in_latest',
            field=models.BooleanField(default=True),
        ),
    ]
