# Generated by Django 3.0.4 on 2020-04-01 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0006_auto_20200401_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxpage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='boxpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Face of the deck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='boxpage',
            name='order_by_latest',
            field=models.BooleanField(default=True),
        ),
    ]
