# Generated by Django 3.0.4 on 2020-04-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0010_auto_20200401_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooklepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Face of the card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
